### ISSUE TITLE
TypeError: assets is not iterable

### ISSUE THREAD

**Issue by db-it** [MCJack123/ghaction-Generate-Release-Hashes#7]
I'm encountering the following error:

```
Run MCJack123/ghaction-generate-release-hashes@v4
  with:
    hash-type: sha256
    file-name: checksums.txt
    get-assets: true
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.[11](https://github.com/db-it/warp-dev-backup/actions/runs/8023260964/job/21919406073#step:7:11).8/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.11.8/x64/lib
  
file:///home/runner/work/_actions/MCJack[12](https://github.com/USER/REPO/actions/runs/8023260964/job/21919406073#step:7:12)3/ghaction-generate-release-hashes/v4/index.js:[13](https://github.com/USER/REPO/actions/runs/8023260964/job/21919406073#step:7:13)
    for (const asset of assets) {
                        ^
TypeError: assets is not iterable
    at run (file:///home/runner/work/_actions/MCJack123/ghaction-generate-release-hashes/v4/index.js:13:25)
    at file:///home/runner/work/_actions/MCJack123/ghaction-generate-release-hashes/v4/index.js:33:88
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

This is the workflow I' using:

```yml
on:
  release:
    types: [published]

permissions:
  contents: write

name: Release
jobs:
  build:
    name: Build release assets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: python -m pip install --upgrade pip build

      - name: Build package
        run: python -m build

      - name: Upload distribution packages to release
        uses: svenstaro/upload-release-action@v2
        with:
          file_glob: true
          file: dist/*
          overwrite: true
          tag: ${{ github.ref }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate checksums
        uses: MCJack123/ghaction-generate-release-hashes@v4
        with:
          hash-type: sha256
          file-name: checksums.txt
          get-assets: true
```
